### ISSUE TITLE
Image metadata should be imported

### ISSUE THREAD

**Issue by hsaginor** [headwirecom/helix-sportsmagazine#14] opened 2022-12-22 21:37 UTC

**Comment by hsaginor** [comment] 2023-08-16 05:40
@icaraps I don't really know how to handle this yet. The importer tool does not help. And where would we store image metadata?

**Comment by icaraps** [comment] 2023-08-16 14:29
@hsaginor can you share examples of image metadata ? Currently we mostly store it as section metadata in the document after the image.

**Comment by icaraps** [comment] 2023-09-14 05:24
@hsaginor  I think this ticket is a duplicate of the alt image issue so it can closed WDYT ?

**Comment by hsaginor** [comment] 2023-09-14 06:49
@icaraps 

> I think this ticket is a duplicate of the alt image issue so it can closed WDYT ?
Quite possible. This was opened a long time ago because Ruben was asking how we can import image metadata. Though, I am not sure what other image metadata we could be importing in Franklin

**Closed** 2024-01-12 19:47 UTC
Labels: Import
